use std::collections::HashMap;
use std::env;
use std::fs;
use std::io::ErrorKind;
use std::path::{Path, PathBuf};
use std::process::Command;

use crate::ast::{BinaryOp, Expr, Function, Program, Stmt, Type, UnaryOp};

#[derive(Debug, Clone)]
struct Signature {
    params: Vec<Type>,
    return_type: Type,
}

#[derive(Debug, Clone)]
pub struct NativeArtifact {
    pub source: PathBuf,
    pub executable: PathBuf,
    pub compiler: String,
    pub release: bool,
}

pub fn build_native(
    program: &Program,
    project_root: &Path,
    project_name: &str,
    release: bool,
) -> Result<NativeArtifact, String> {
    let build_dir = project_root.join("build");
    fs::create_dir_all(&build_dir)
        .map_err(|error| format!("could not create build directory: {error}"))?;

    let source = build_dir.join(format!("{project_name}.c"));
    let executable_name = if cfg!(windows) {
        format!("{project_name}.exe")
    } else {
        project_name.to_string()
    };
    let executable = build_dir.join(executable_name);

    let generated = emit_c(program)?;
    fs::write(&source, generated)
        .map_err(|error| format!("could not write native C source {}: {error}", source.display()))?;

    let compiler = compile_c(&source, &executable, release)?;

    Ok(NativeArtifact {
        source,
        executable,
        compiler,
        release,
    })
}

pub fn emit_c(program: &Program) -> Result<String, String> {
    Generator::new(program)?.generate(program)
}

struct Generator {
    signatures: HashMap<String, Signature>,
    scopes: Vec<HashMap<String, Type>>,
    output: String,
    indent: usize,
}

impl Generator {
    fn new(program: &Program) -> Result<Self, String> {
        let mut signatures = HashMap::new();
        for function in &program.functions {
            if signatures
                .insert(
                    function.name.clone(),
                    Signature {
                        params: function.params.iter().map(|param| param.ty).collect(),
                        return_type: function.return_type,
                    },
                )
                .is_some()
            {
                return Err(format!("native backend: duplicate function '{}'", function.name));
            }
        }

        Ok(Self {
            signatures,
            scopes: Vec::new(),
            output: String::new(),
            indent: 0,
        })
    }

    fn generate(mut self, program: &Program) -> Result<String, String> {
        self.output.push_str("/* Generated by the Genix native C11 backend. */\n");
        self.output.push_str("#include <stdbool.h>\n");
        self.output.push_str("#include <stdint.h>\n");
        self.output.push_str("#include <stdio.h>\n");
        self.output.push_str("#include <stdlib.h>\n");
        self.output.push_str("#include <string.h>\n\n");

        self.emit_runtime();
        self.output.push('\n');

        for function in &program.functions {
            self.output.push_str(&self.function_signature(function, true));
            self.output.push_str(";\n");
        }
        self.output.push('\n');

        for function in &program.functions {
            self.emit_function(function)?;
            self.output.push('\n');
        }

        self.output.push_str("int main(void) {\n");
        self.output.push_str("    gb_fn_main();\n");
        self.output.push_str("    return 0;\n");
        self.output.push_str("}\n");

        Ok(self.output)
    }

    fn emit_runtime(&mut self) {
        self.output.push_str(
            "static char* gb_concat(const char* left, const char* right) {\n\
    size_t left_len = strlen(left);\n\
    size_t right_len = strlen(right);\n\
    char* result = (char*)malloc(left_len + right_len + 1);\n\
    if (result == NULL) {\n\
        fputs(\"Genix runtime error: out of memory\\n\", stderr);\n\
        exit(70);\n\
    }\n\
    memcpy(result, left, left_len);\n\
    memcpy(result + left_len, right, right_len);\n\
    result[left_len + right_len] = '\\0';\n\
    return result;\n\
}\n",
        );
    }

    fn function_signature(&self, function: &Function, is_static: bool) -> String {
        let prefix = if is_static { "static " } else { "" };
        let params = if function.params.is_empty() {
            "void".to_string()
        } else {
            function
                .params
                .iter()
                .map(|param| format!("{} {}", c_type(param.ty), c_variable_name(&param.name)))
                .collect::<Vec<_>>()
                .join(", ")
        };

        format!(
            "{prefix}{} {}({params})",
            c_type(function.return_type),
            c_function_name(&function.name)
        )
    }

    fn emit_function(&mut self, function: &Function) -> Result<(), String> {
        self.output.push_str(&self.function_signature(function, true));
        self.output.push_str(" {\n");
        self.indent = 1;
        self.scopes = vec![HashMap::new()];

        for param in &function.params {
            self.scopes[0].insert(param.name.clone(), param.ty);
        }

        for statement in &function.body {
            self.emit_statement(statement)?;
        }

        self.scopes.clear();
        self.indent = 0;
        self.output.push_str("}\n");
        Ok(())
    }

    fn emit_statement(&mut self, statement: &Stmt) -> Result<(), String> {
        match statement {
            Stmt::Let {
                name,
                value,
                annotation,
                ..
            } => {
                let (code, inferred) = self.emit_expr(value)?;
                let ty = annotation.unwrap_or(inferred);
                self.line(format!(
                    "{} {} = {};",
                    c_type(ty),
                    c_variable_name(name),
                    code
                ));
                self.current_scope_mut()?.insert(name.clone(), ty);
            }
            Stmt::Assign { name, value } => {
                let (code, _) = self.emit_expr(value)?;
                if self.lookup_type(name).is_none() {
                    return Err(format!("native backend: undefined variable '{name}'"));
                }
                self.line(format!("{} = {};", c_variable_name(name), code));
            }
            Stmt::Print(expr) => {
                let (code, ty) = self.emit_expr(expr)?;
                let statement = match ty {
                    Type::Int => format!("printf(\"%lld\\n\", (long long)({code}));"),
                    Type::Float => format!("printf(\"%.15g\\n\", (double)({code}));"),
                    Type::Bool => format!(
                        "printf(\"%s\\n\", ({code}) ? \"true\" : \"false\");"
                    ),
                    Type::String => format!("printf(\"%s\\n\", {code});"),
                    Type::Void => {
                        return Err("native backend: cannot print a void expression".into())
                    }
                };
                self.line(statement);
            }
            Stmt::Expr(expr) => {
                let (code, _) = self.emit_expr(expr)?;
                self.line(format!("{code};"));
            }
            Stmt::Return(Some(expr)) => {
                let (code, _) = self.emit_expr(expr)?;
                self.line(format!("return {code};"));
            }
            Stmt::Return(None) => self.line("return;"),
            Stmt::If {
                condition,
                then_branch,
                else_branch,
            } => {
                let (condition, _) = self.emit_expr(condition)?;
                self.line(format!("if ({condition}) {{"));
                self.indent += 1;
                self.push_scope();
                for statement in then_branch {
                    self.emit_statement(statement)?;
                }
                self.pop_scope();
                self.indent -= 1;

                if let Some(else_branch) = else_branch {
                    self.line("} else {");
                    self.indent += 1;
                    self.push_scope();
                    for statement in else_branch {
                        self.emit_statement(statement)?;
                    }
                    self.pop_scope();
                    self.indent -= 1;
                }
                self.line("}");
            }
            Stmt::While { condition, body } => {
                let (condition, _) = self.emit_expr(condition)?;
                self.line(format!("while ({condition}) {{"));
                self.indent += 1;
                self.push_scope();
                for statement in body {
                    self.emit_statement(statement)?;
                }
                self.pop_scope();
                self.indent -= 1;
                self.line("}");
            }
            Stmt::Block(body) => {
                self.line("{");
                self.indent += 1;
                self.push_scope();
                for statement in body {
                    self.emit_statement(statement)?;
                }
                self.pop_scope();
                self.indent -= 1;
                self.line("}");
            }
        }
        Ok(())
    }

    fn emit_expr(&self, expr: &Expr) -> Result<(String, Type), String> {
        match expr {
            Expr::Integer(value) => Ok((format!("INT64_C({value})"), Type::Int)),
            Expr::Float(value) => Ok((format_float(*value), Type::Float)),
            Expr::Bool(value) => Ok((if *value { "true" } else { "false" }.into(), Type::Bool)),
            Expr::String(value) => Ok((format!("\"{}\"", escape_c_string(value)), Type::String)),
            Expr::Variable(name) => self
                .lookup_type(name)
                .map(|ty| (c_variable_name(name), ty))
                .ok_or_else(|| format!("native backend: undefined variable '{name}'")),
            Expr::Call { callee, arguments } => {
                let signature = self
                    .signatures
                    .get(callee)
                    .ok_or_else(|| format!("native backend: undefined function '{callee}'"))?;

                if signature.params.len() != arguments.len() {
                    return Err(format!(
                        "native backend: function '{callee}' expected {} arguments, found {}",
                        signature.params.len(),
                        arguments.len()
                    ));
                }

                let args = arguments
                    .iter()
                    .map(|argument| self.emit_expr(argument).map(|(code, _)| code))
                    .collect::<Result<Vec<_>, _>>()?
                    .join(", ");
                Ok((
                    format!("{}({args})", c_function_name(callee)),
                    signature.return_type,
                ))
            }
            Expr::Unary { op, expr } => {
                let (code, ty) = self.emit_expr(expr)?;
                match op {
                    UnaryOp::Negate => Ok((format!("(-({code}))"), ty)),
                    UnaryOp::Not => Ok((format!("(!({code}))"), Type::Bool)),
                }
            }
            Expr::Binary { left, op, right } => {
                let (left_code, left_type) = self.emit_expr(left)?;
                let (right_code, right_type) = self.emit_expr(right)?;

                match op {
                    BinaryOp::Add if left_type == Type::String && right_type == Type::String => Ok((
                        format!("gb_concat(({left_code}), ({right_code}))"),
                        Type::String,
                    )),
                    BinaryOp::Add => Ok((
                        format!("(({left_code}) + ({right_code}))"),
                        numeric_result(left_type, right_type)?,
                    )),
                    BinaryOp::Subtract => Ok((
                        format!("(({left_code}) - ({right_code}))"),
                        numeric_result(left_type, right_type)?,
                    )),
                    BinaryOp::Multiply => Ok((
                        format!("(({left_code}) * ({right_code}))"),
                        numeric_result(left_type, right_type)?,
                    )),
                    BinaryOp::Divide => Ok((
                        format!("(({left_code}) / ({right_code}))"),
                        numeric_result(left_type, right_type)?,
                    )),
                    BinaryOp::Equal | BinaryOp::NotEqual
                        if left_type == Type::String && right_type == Type::String =>
                    {
                        let comparison = if matches!(op, BinaryOp::Equal) { "==" } else { "!=" };
                        Ok((
                            format!("(strcmp(({left_code}), ({right_code})) {comparison} 0)"),
                            Type::Bool,
                        ))
                    }
                    BinaryOp::Equal => Ok((
                        format!("(({left_code}) == ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::NotEqual => Ok((
                        format!("(({left_code}) != ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::Less => Ok((
                        format!("(({left_code}) < ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::LessEqual => Ok((
                        format!("(({left_code}) <= ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::Greater => Ok((
                        format!("(({left_code}) > ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::GreaterEqual => Ok((
                        format!("(({left_code}) >= ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::And => Ok((
                        format!("(({left_code}) && ({right_code}))"),
                        Type::Bool,
                    )),
                    BinaryOp::Or => Ok((
                        format!("(({left_code}) || ({right_code}))"),
                        Type::Bool,
                    )),
                }
            }
        }
    }

    fn line(&mut self, line: impl AsRef<str>) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
        self.output.push_str(line.as_ref());
        self.output.push('\n');
    }

    fn current_scope_mut(&mut self) -> Result<&mut HashMap<String, Type>, String> {
        self.scopes
            .last_mut()
            .ok_or_else(|| "native backend: no active variable scope".to_string())
    }

    fn lookup_type(&self, name: &str) -> Option<Type> {
        self.scopes
            .iter()
            .rev()
            .find_map(|scope| scope.get(name).copied())
    }

    fn push_scope(&mut self) {
        self.scopes.push(HashMap::new());
    }

    fn pop_scope(&mut self) {
        self.scopes.pop();
    }
}

fn compile_c(source: &Path, executable: &Path, release: bool) -> Result<String, String> {
    let candidates = compiler_candidates();
    let mut missing = Vec::new();

    for compiler in candidates {
        let mut command = Command::new(&compiler);
        command.arg("-std=c11");
        if release {
            command.arg("-O2");
        } else {
            command.arg("-O0").arg("-g");
        }
        command.arg(source).arg("-o").arg(executable);

        match command.output() {
            Ok(output) if output.status.success() => return Ok(compiler),
            Ok(output) => {
                let stderr = String::from_utf8_lossy(&output.stderr);
                let stdout = String::from_utf8_lossy(&output.stdout);
                return Err(format!(
                    "native C compiler '{compiler}' failed\n{}{}",
                    stdout,
                    stderr
                ));
            }
            Err(error) if error.kind() == ErrorKind::NotFound => missing.push(compiler),
            Err(error) => {
                return Err(format!("could not start native C compiler '{compiler}': {error}"))
            }
        }
    }

    Err(format!(
        "no C compiler found (tried {}); install cc, clang, or gcc, or set the CC environment variable",
        missing.join(", ")
    ))
}

fn compiler_candidates() -> Vec<String> {
    let mut result = Vec::new();
    if let Ok(cc) = env::var("CC") {
        let cc = cc.trim();
        if !cc.is_empty() {
            result.push(cc.to_string());
        }
    }

    for compiler in ["cc", "clang", "gcc"] {
        if !result.iter().any(|candidate| candidate == compiler) {
            result.push(compiler.to_string());
        }
    }
    result
}

fn c_type(ty: Type) -> &'static str {
    match ty {
        Type::Int => "int64_t",
        Type::Float => "double",
        Type::Bool => "bool",
        Type::String => "const char*",
        Type::Void => "void",
    }
}

fn numeric_result(left: Type, right: Type) -> Result<Type, String> {
    match (left, right) {
        (Type::Int, Type::Int) => Ok(Type::Int),
        (Type::Int, Type::Float)
        | (Type::Float, Type::Int)
        | (Type::Float, Type::Float) => Ok(Type::Float),
        _ => Err(format!(
            "native backend: numeric operation requires int/float, found {left} and {right}"
        )),
    }
}

fn c_function_name(name: &str) -> String {
    format!("gb_fn_{}", sanitize_identifier(name))
}

fn c_variable_name(name: &str) -> String {
    format!("gb_v_{}", sanitize_identifier(name))
}

fn sanitize_identifier(value: &str) -> String {
    value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect()
}

fn format_float(value: f64) -> String {
    if value.is_finite() {
        let mut text = format!("{value:.17}");
        while text.contains('.') && text.ends_with('0') {
            text.pop();
        }
        if text.ends_with('.') {
            text.push('0');
        }
        text
    } else {
        "0.0".to_string()
    }
}

fn escape_c_string(value: &str) -> String {
    let mut output = String::new();
    for ch in value.chars() {
        match ch {
            '\\' => output.push_str("\\\\"),
            '"' => output.push_str("\\\""),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            ch if ch.is_control() => output.push_str(&format!("\\x{:02x}", ch as u32)),
            ch => output.push(ch),
        }
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{lexer, parser, typechecker};

    fn compile_source(source: &str) -> Program {
        let program = parser::parse(lexer::lex(source).unwrap()).unwrap();
        typechecker::check(&program).unwrap();
        program
    }

    #[test]
    fn emits_native_c_for_typed_function() {
        let program = compile_source(
            "fn add(a: int, b: int) -> int { return a + b; } fn main() { let x: int = add(20, 22); print(x); }",
        );
        let c = emit_c(&program).unwrap();
        assert!(c.contains("static int64_t gb_fn_add"));
        assert!(c.contains("gb_fn_add(INT64_C(20), INT64_C(22))"));
        assert!(c.contains("int main(void)"));
    }

    #[test]
    fn emits_string_runtime_support() {
        let program = compile_source(
            "fn greet(name: string) -> string { return \"Hello \" + name; } fn main() { print(greet(\"Genix\")); }",
        );
        let c = emit_c(&program).unwrap();
        assert!(c.contains("gb_concat"));
        assert!(c.contains("printf(\"%s\\n\""));
    }
}
